
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.compi.emuladorinstruccionsql.jcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int COLUMNA = 12;
  public static final int AND = 9;
  public static final int SEMICOLON = 11;
  public static final int PLUS = 16;
  public static final int INSERTAR = 4;
  public static final int OR = 10;
  public static final int DECIMAL = 28;
  public static final int GREATER_THAN = 22;
  public static final int PARIZQ = 23;
  public static final int PARDER = 24;
  public static final int MENORQ = 25;
  public static final int FILTRAR = 3;
  public static final int VALORES = 5;
  public static final int ASIGNAR = 7;
  public static final int EQUALS = 20;
  public static final int STRING = 14;
  public static final int ACTUALIZAR = 6;
  public static final int MAYORQ = 26;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int DIVIDE = 19;
  public static final int LESS_THAN = 21;
  public static final int MINUS = 17;
  public static final int error = 1;
  public static final int ARCHIVO = 13;
  public static final int EN = 8;
  public static final int ENTERO = 27;
  public static final int SELECCIONAR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECCIONAR",
  "FILTRAR",
  "INSERTAR",
  "VALORES",
  "ACTUALIZAR",
  "ASIGNAR",
  "EN",
  "AND",
  "OR",
  "SEMICOLON",
  "COLUMNA",
  "ARCHIVO",
  "STRING",
  "NUMBER",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQUALS",
  "LESS_THAN",
  "GREATER_THAN",
  "PARIZQ",
  "PARDER",
  "MENORQ",
  "MAYORQ",
  "ENTERO",
  "DECIMAL"
  };
}

